version: 2
updates:
  - package-ecosystem: npm
    directory: /api-gateway-node
    schedule:
      interval: weekly
    labels:
      - dependencies
      - javascript

  - package-ecosystem: pip
    directory: /trading-service-python
    schedule:
      interval: weekly
    labels:
      - dependencies
      - python

  - package-ecosystem: pip
    directory: /ai-service-python
    schedule:
      interval: weekly
    labels:
      - dependencies
      - python

  - package-ecosystem: maven
    directory: /user-service-java
    schedule:
      interval: weekly
    labels:
      - dependencies
      - java

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels:
      - dependencies
      - github-actions
